name名称：使用Conda的Python包   名字: Python Package using Conda

on   在(推)   在(推)::   在: [push]

jobs   工作:
  build-linux:
    runs-on   上运行:ubuntu-latest   运行在   上运行:ubuntu-latest: ubuntu-latest
    strategy   策略:
      max-parallel: 5

    steps   步骤:
    - —用途：actions/checkout@v4—用途：actions/checkout@v4uses: actions/checkout@v4
    - - name：设置Python 3.10- name：设置Python 3.10name: Set up Python 3.10
      uses用途:行动/ setup-python@v3   使用用途:行动/ setup-python@v3: actions/setup-python@v3
      with   与:
        python-version   python版本: '3.10'
    - —名称：将“conda”添加到“系统路径”—名称：将“conda”添加到“系统路径”name: Add conda to system path
      run   运行: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory# $CONDA是一个指向miniconda目录根目录的环境变量
        echo $CONDA/bin >> $GITHUB_PATH
    - —名称：安装依赖—名称：安装依赖—名称：安装依赖name: Install dependencies
      run   运行: |
        conda env update --file environment.yml --name baseConda env update -文件环境。Yml——名称基础
    - -名称：flake8 Lintname: Lint with flake8
      run   运行: |
        conda install flake8   安装flake8
        # stop the build if there are Python syntax errors or undefined names#如果出现Python语法错误或未定义名称，则停止构建
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statisticsflake8。——count——select=E9,F63,F7,F82——show-source——statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide# exit-zero将所有错误视为警告。GitHub编辑器有127个字符宽
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statisticsflake8。——count——exit-zero——max-complexity=10——max-line-length=127——统计信息
    - -名称：Test with pytestname: Test with pytest
      run   运行: |
        conda install pytest   Conda安装pytest
        pytest
